config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end

  resources :recipe_foods
  resources :foods 
  resources :recipes
  get 'recipes_public', to: 'recipes#public_list', as: 'recipes_public_list'
  patch 'recipes/:id/update_public', to: 'recipes#update_public', as: 'update_public'

  resources :users
  resources :foods do
    member do
      delete 'delete', to: 'foods#destroy', as: 'delete'
    end
  end

  # Defines the root path route ("/")
  root 'recipes#index'

  resources :shopping_list, only: [:index]

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods

  validates :name, presence: true, length: { maximum: 50 }
  validates :preparation_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :description, presence: true, length: { maximum: 1000 }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recipe, except: %i[index new create public_list]

  rescue_from ActiveRecord::InvalidForeignKey, with: :invalid_foreign_key

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  def public_list
    # @recipes = Recipe.where(public: true).includes(:user)
    @recipes = Recipe.where(public: true)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @modify = current_user.id == @recipe.user_id
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_public
    @recipe.update(public: !@recipe.public)
    redirect_to recipe_url(@recipe)
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end

  def invalid_foreign_key(_exception)
    redirect_to recipes_url, alert: "Can't delete recipe because it already has foods."
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.number_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.number_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

    <%= form.hidden_field :user_id, value: current_user.id %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
    <li class="list-group-item mb-1 container">
    <div class=row>
      <div class="col-3">
        <%= content_tag :h3, recipe.name %>
        <%= button_to "REMOVE", recipe, method: :delete, class:"btn btn-danger" %>
      </div>
      <%= content_tag :p, recipe.description.truncate(200), class:'col ps-5 text-start' %>
    </div>
    </li>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <h1 class="display-4 py-3">My Recipes</h1>
  <div class="row py-1">
    <div class="col-12 text-right label-right">
      <%= button_to "New recipe", { :action => "new" }, method: :get, class:"btn btn-primary px-sm-2 px-md-3"%>
    </div>
  </div>

  <ul class = "list-group">
    <% @recipes.each do |recipe| %>
        <%= link_to (render recipe), recipe, class:'text-decoration-none' %>
    <% end %>
  <ul>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/public_list.html.erb
<div class="container">
  <h1 class="display-4 py-3">Public Recipes</h1>

  <ul class = "list-group">
    <% @recipes.includes(:user).each do |recipe| %>
      <li class="list-group-item mb-1 container">
      <div class=row>
        <div class="col">
          <h3><%= link_to recipe.name, recipe, class: "text-decoration-none color text-reset"%><h3>
          <%= content_tag :p, "By: #{recipe.user.name}" %>
        </div>
        <div class='col'>
          <%= content_tag :p, "Total food items: #{recipe.foods.count}" %>
          <%= content_tag :p, "Total Price: #{recipe.recipe_foods.includes(:food).map{|f| f.quantity * f.food.price}.sum}"%>
        </div>
      </div>
      </li>
    <% end %>
  <ul>

</div>

app/views/recipes/show.html.erb
<div class = "container">
<%= content_tag :h1, @recipe.name %>
<div class="row row-cols-2 text-start">
  <%= content_tag :p, "Preparation time: #{@recipe.preparation_time}", class: "col-6" %>
  <% if @modify %>
  <div class='col-6 text-end'> <%= button_to @recipe.public ? 'Is Public' : 'Is Private', update_public_path, method: :patch %> </div>
  <% end %>
  <%= content_tag :p, "Cooking Time: #{@recipe.cooking_time}", class: "col-12" %>
  <%= content_tag :p, "Instructions: #{@recipe.description}", class: "col-12" %>
  <% if @modify %>
  <%= button_to 'Generate shopping list', shopping_list_index_path, method: :get, class: "col-6" %>
  <div class='col-6 text-end'> <%= button_to 'Add ingredient', new_recipe_food_path(@recipe), method: :get %> </div>
  <% end %>
</div>
<hr>
<table class='table table-striped'>
  <tr>
    <th>food</th>
    <th>Quantity</th>
    <th>Value</th>
    <% if @modify %>
      <th>Actions</th>
    <% end %>
  </tr>
  <% @recipe.recipe_foods.includes(:food).each do |rf| %>
   <tr>
      <td><%= rf.food.name %></td>
    <td><%= "#{rf.quantity} #{rf.food.measurement_unit}" %></td>
      <td><%= rf.food.price*rf.quantity %></td>
      <% if @modify %>
      <td class= "d-flex flex-row justify-content-center">
        <%= button_to 'Modify', edit_recipe_food_path(rf), method: :get %>
        <%= button_to 'Remove', recipe_food_path(rf), method: :delete %> 
      </td>
      <% end %>
    </tr>
  <% end %>
</div>
</table>
<% if @modify %>
<div>
  <%= link_to "Edit this recipe", edit_recipe_path(@recipe) %> |
  <%= link_to "Back to recipes", recipes_path %>

  <%= button_to "Destroy this recipe", @recipe, method: :delete, class:"btn btn-danger" %>
</div>
<% end %>