config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end

  resources :recipe_foods
  resources :foods 
  resources :recipes
  get 'recipes_public', to: 'recipes#public_list', as: 'recipes_public_list'
  patch 'recipes/:id/update_public', to: 'recipes#update_public', as: 'update_public'

  resources :users
  resources :foods do
    member do
      delete 'delete', to: 'foods#destroy', as: 'delete'
    end
  end

  # Defines the root path route ("/")
  root 'recipes#index'

  resources :shopping_list, only: [:index]

end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true, length: { maximum: 50 }
  validates :measurement_unit, presence: true, length: { maximum: 20 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]
  before_action :authenticate_user!

  rescue_from ActiveRecord::InvalidForeignKey, with: :invalid_foreign_key

  # GET /foods or /foods.json
  def index
    # select all foods that belongs to the current user
    @foods = current_user.foods
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)
    @food.user = current_user # Assign the current user to the food's user_id

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully deleted' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end

  def invalid_foreign_key(_exception)
    redirect_to foods_url, alert: "Can't delete food because it's used in a recipe."
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Measurement unit:</strong>
    <%= food.measurement_unit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= number_to_currency(food.price) %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= food.quantity %>
  </p>

</div>

app/views/foods/_form.html.erb
<div class='container pt-3'>
  <%= form_with(model: food) do |form| %>
    <% if food.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

        <ul>
          <% food.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="d-flex flex-row align-items-center justify-content-center mb-2">
      <%= form.label :name, class: 'col-form-label col-2 label-right px-2' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="d-flex flex-row align-items-center justify-content-center mb-2 ">
      <%= form.label 'M/Unit:', class: 'col-form-label col-4 label-right px-2' %>
      <%= form.select :measurement_unit, FIXED_MEASUREMENT_UNITS, { prompt: "Select a Measurement Unit" }, class: 'form-control' %>
    </div>

    <div class="d-flex flex-row align-items-center justify-content-center mb-2">
      <%= form.label :price, class: 'col-form-label col-4 label-right px-2' %>
      <%= form.text_field :price, class: 'form-control' %>
    </div>

    <div class="d-flex flex-row align-items-center justify-content-center mb-2">
      <%= form.label :quantity, class: 'col-form-label col-4 label-right px-2' %>
      <%= form.number_field :quantity, class: 'form-control' %>
    </div>

    <div  class="mt-5">
      <%= form.submit class: 'btn btn-primary btn-sm' %>
    </div>
  <% end %>
</div>

app/views/foods/edit.html.erb
<div class='container py-2 border rounded shadow bg-white bg-opacity-10 center'>
  <h1>Editing food</h1>

  <%= render "form", food: @food %>

  <br>

  <div class="container mt-3">
    <%= link_to "Cancel and Back to foods", foods_path, class: 'btn btn-secondary btn-sm mr-4' %>
  </div>

</div>

app/views/foods/index.html.erb
<div class="container">

  <h1 class="display-4 py-3">Foods</h1>
  <div class="row py-1">
    <div class="col-12 text-right label-right">
      <%= link_to "Add Food", new_food_path, class: 'btn btn-primary px-sm-2 px-md-3' %>
    </div>
  </div>
  
  <table class="table table-striped table-bordered rounded shadow">
    <thead>
      <tr>
        <th>Food</th>
        <th>Measurement Unit</th>
        <th>Unit Price</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= link_to(food.name, food_path(food)) %></td>
          <td><%= food.measurement_unit %></td>
          <td><%= number_to_currency(food.price) %></td>
          <td>
            <div class="container text-center d-flex justify-content-center gap-1">
              <%= form_with(url: delete_food_path(food), method: :delete, remote: true) do |form| %>
                <%= form.button type: :submit, class: 'btn btn-danger btn-sm', data: { confirm: 'Are you sure you?' } do %>
                  Delete
                <% end %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<div class='container py-2 mt-5 border rounded shadow bg-white bg-opacity-10 center'>
  <h1>New food</h1>

  <%= render "form", food: @food %>

  <br>

  <div>
    <%= link_to "Cancel and Back to foods", foods_path, class: 'btn btn-secondary btn-sm mr-4' %>
  </div>
</div>

app/views/foods/show.html.erb
<div class='container py-2 mt-5 border rounded shadow bg-white bg-opacity-10 center'>
  <h1 class='py-4'>Food Details</h1>
    
  <%= render @food %>

  <div class="container mt-3">
    <div class="d-flex justify-content-center gap-2 py-4">
      <%= link_to "Edit this food", edit_food_path(@food), class: 'btn btn-secondary btn-sm mr-4' %>
      <%= link_to "Back to foods", foods_path, class: 'btn btn-secondary btn-sm mr-4' %>
      <%= button_to "Delete this food", @food, method: :delete, class: 'btn btn-danger btn-sm' %>
    </div>
  </div>
</div>